CREATE TABLE bookmarks (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL,
	url text NOT NULL,
	desc text NOT NULL,
	rating numeric NOT NULL,
	CONSTRAINT bookmarks_pkey PRIMARY KEY (id)
);